default_platform(:ios)

platform :ios do
  desc("Run unit and UI tests on iPhone 15 simulator")
  lane :test do
    scan(
      scheme: "ParsePushHelper",
      devices: ["iPhone 15"],
      clean: true,
      code_coverage: true
    )
  end

  desc("Build beta release for TestFlight")
  lane :beta do
    match(type: "appstore")
    gym(
      scheme: "ParsePushHelper",
      export_method: "app-store"
    )
    pilot
  end
end
